ribbit/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ribbit_app.urls'))
]

ribbit_app/models.py
from django.db import models
from django.contrib.auth.models import User
import hashlib


class Ribbit(models.Model):
    content = models.CharField(max_length=140)
    user = models.ForeignKey(User)
    creation_date = models.DateTimeField(auto_now=True, blank=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False)

    def gravatar_url(self):
        return "http://www.gravatar.com/avatar/%s?s=50" % hashlib.md5(self.user.email.encode('utf-8')).hexdigest()


'''
This line create a user if it is not present and sets the profile attribute (which is created dynamically) of User class
to it.
So, whenever user.profile is called it will come to this line and return or create and return a user
'''
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

ribbit/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet/less" href="{% static 'ribbit_app/style.less' %}">
    <script src="{% static 'ribbit_app/less.js' %}"></script>
</head>
<body>
    <header>
        <div class="wrapper">
            <img src="{% static 'ribbit_app/gfx/logo.png' %}">
            <span>Twitter Clone</span>
            {% block login %}
            <a href="/users">Home</a>
            <a href="/users">Public Profiles</a>
            <a href="/users/{{ username }}">My Profiles</a>
            <a href="/ribbits">Public Ribbits</a>
            <form action="/logout">
                <input type="submit" id="btnLogOut" value="Log Out">
            </form>
            {% endblock %}
        </div>>
    </header>>
    <div id="content">
        <div class="wrapper">
            {% block flash %}
            {% if auth_form.non_field_errors or user_form.non_field_errors or ribbit_form.errors %}
            <div class="flash error">
                {{ auth_form.non_field_errors }}
                {{ user_form.non_field_errors }}
                {{ ribbit_form.content.errors }}
            </div>
            {% endif %}
            {% if notice %}
            <div class="flash notice">
                {{ notice }}
            </div>
            {% endif %}
            {% endblock %}

            {% block content %}

            {% endblock %}
        </div>
    </div>
    <footer>
        <div class="wrapper">
            Ribbit - A Twitter Clone Tutorial
            <a href="http://net.tutsplus.com">
                <img src="{% static 'ribbit_app/gfx/logo-nettuts.png' %}">
            </a>
            <a>
                <img src="https://www.djangoproject.com/m/img/badges/djangomade124x25.gif" border="0" alt="Made with Django." title="Made with Django."/>
            </a>
        </div>
    </footer>
</body>
</html>

ribbit/templates/buddies.html
{% extends "base.html" %}
{% block login %}
    {% with user.username as username %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}
    <div class="panel right">
        <h1> Create a Ribbit!</h1>
        <p>
            <form action="/submit" method="post">
            {% for field in ribbit_form %}{% csrf_token %}
            {{ field }}
            {% endfor %}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <input type="submit" value="Ribbit!">
            </form>
        </p>
    </div>
    <div class="panel left">
        <h1>Buddies' Ribbits</h1>
        {% for ribbit in ribbits %}
        <div class="ribbitWrapper">
            <a href="/users/{{ ribbit.user.username }}">
                <img class="avatar" src="{{ ribbit.user.profile.gravatar_url }}">
                <span class="name">{{ ribbit.user.first_name }}</span>
            </a>
            @{{ ribbit.user.username }}
            <p>
                {{ ribbit.content }}
            </p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

ribbit/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block login %}
    <form action="/login" method="post">{% csrf_token %}
        {% for field in auth_form %}
        {{ field }}
        {% endfor %}
        <input type="submit" id="btnLogIn" value="Log In">
    </form>
{% endblock %}

{% block content %}
{% if auth_form.non_field_errors or user_form.non_field_errors %}
<div class="flash error">
    {{ auth_form.non_field_errors }}
    {{ user_form.non_field_errors }}
</div>
{% endif %}
<img src="{% static 'ribbit_app/gfx/frog.jpg' %}">
<div class="panel right">
    <h1>New to Ribbit?</h1>
    <p>
        <form action="/signup" method="post">{% csrf_token %}
            {% for field in user_form %}
            {{ field }}
            {% endfor %}
            <input type="submit" value="Create Account">
        </form>
    </p>
</div>
{% endblock %}

ribbit/templates/profiles.html
{% extends "base.html" %}

{% block content %}
    <div class="panel right">
        <h1>Create a Ribbit</h1>
        <p>
            <form action="/submit" method="post">
            {% for field in ribbit_form %}{% csrf_token %}
            {{ field }}
            {% endfor %}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <input type="submit" value="Ribbit!">
            </form>
        </p>
    </div>
    <div class="panel left">
        <h1> Public Profiles</h1>
        {% for users, ribbit in obj %}
        <div class="ribbitWrapper">
            <a href="/users/{{ users.username }}">
                <img class="avatar" src="{{ users.profile.gravatar_url }}">
                <span class="name">{{ users.first_name }}</span>
            </a>
            @{{ users.username }}
            <p>
                {{ users.ribbit__count }} Ribbits
                <span class="spacing">{{ user.profile.followed_by.count }} Followers</span>
                <span class="spacing">{{ user.profile.follows.count }} Following</span>
            </p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

ribbit/templates/public.html
{% extends "base.html" %}

{% block content %}
    <div class="panel right">
        <h1>Create a Ribbit</h1>
        <p>
            <form action="/submit" method="post">
            {% for field in ribbit_form %}{% csrf_token %}
            {{ field }}
            {% endfor %}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <input type="submit" value="Ribbit!">
            </form>
        </p>
    </div>
    <div class="panel left">
        <h1>Public Ribbits</h1>
        {% for ribbit in ribbits %}
        <div class="ribbitWrapper">
            <img class="avatar" src="{{ ribbit.user.profile.gravatar_url }}">
            <span class="name">{{ ribbit.user.first_name }}</span>@{{ ribbit.user.username }}
            <span class="time">{{ ribbit.creation_date|timesince }}</span>
            <p>{{ ribbit.content }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

ribbit/templates/user.html
{% extends "base.html" %}
{% block login %}
    {% with user.username as username %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}
    <div class="panel left">
        <h1>{{ user.first_name }}'s Profile</h1>
        <div class="ribbitWrapper">
            <a href="/users/{{ user.username }}">
                <img class="avatar" src="{{ user.profile.gravatar_url }}">
                <span class="name">{{ user.first_name }}</span>
            </a>
            @{{ user.username }}
            <p>
                {{ user.ribbit_set.count }} Ribbits
                <span class="spacing">{{ user.profile.followed_by.count }} Followers</span>
                <span class="spacing">{{ user.profile.follows.count }} Following</span>
            </p>
            {% if follow %}
            <form action="/follow" method="post">
                {% csrf_token %}
                <input type="hidden" name="follow" value="{{ user.id }}">
                <input type="submit" value="Follow">
            </form>
            {% endif %}
        </div>
    </div>

    <div class="panel left">
        <h1>{{ user.first_name }}'s Ribbits</h1>
        {% for ribbit in  ribbits %}
        <div class="ribbitWrapper">
            <a href="/users/{{ user.username }}">
                <img class="avatar" src="{{ user.profile.gravatar_url }}">
                <span class="name">{{ user.first_name }}</span>
            </a>
            @{{ user.username }}
            <span class="time">{{ ribbit.creation_date | timesince }}</span>
            <p>{{ ribbit.content }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}